Products:
    type: entity
    table: products
    id:
        productId:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: product_id
            generator:
                strategy: SEQUENCE
    fields:
        title:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        price:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
        imgurl:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: imgUrl
        manufacturer:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        color:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        width:
            type: integer
            nullable: true
            options:
                unsigned: false
        height:
            type: integer
            nullable: true
            options:
                unsigned: false
        garantie:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
    lifecycleCallbacks: {  }
