Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        surname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        address:
            type: string
            nullable: true
            length: 1024
            options:
                fixed: false
        postalcode:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        city:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        mobilephone:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        mail:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        country:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        gender:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        login:
            type: string
            nullable: true
            length: 1024
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 9999
            options:
                fixed: false
    lifecycleCallbacks: {  }
